// This is an autogenerated file from Firebase Genkit.
'use server';
/**
 * @fileOverview AI-powered product recommendation flow.
 *
 * - getProductRecommendations - A function that handles the product recommendation process.
 * - ProductRecommendationInput - The input type for the getProductRecommendations function.
 * - ProductRecommendationOutput - The return type for the getProductRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ProductRecommendationInputSchema = z.object({
  productSpecifications: z
    .string()
    .describe(
      'Detailed specifications of the products currently being manufactured.'
    ),
});
export type ProductRecommendationInput = z.infer<
  typeof ProductRecommendationInputSchema
>;

const ProductRecommendationOutputSchema = z.object({
  recommendedProducts: z
    .string()
    .describe(
      'A list of recommended products based on the provided specifications.'
    ),
  supplierInformation: z
    .string()
    .describe('Information about the suppliers of the recommended products.'),
});
export type ProductRecommendationOutput = z.infer<
  typeof ProductRecommendationOutputSchema
>;

export async function getProductRecommendations(
  input: ProductRecommendationInput
): Promise<ProductRecommendationOutput> {
  return productRecommendationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'productRecommendationPrompt',
  input: {schema: ProductRecommendationInputSchema},
  output: {schema: ProductRecommendationOutputSchema},
  prompt: `You are an AI assistant that suggests products to purchasing managers based on the specifications of the products they are currently manufacturing.

  Given the following product specifications:
  {{productSpecifications}}

  Recommend a list of products that would be suitable for their needs, and provide information about the suppliers of those products.
  Please format your response as a list of products, each with a brief description and the supplier's name and contact information.
  `,
});

const productRecommendationFlow = ai.defineFlow(
  {
    name: 'productRecommendationFlow',
    inputSchema: ProductRecommendationInputSchema,
    outputSchema: ProductRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
